# Generated by Django 4.1.7 on 2023-03-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendant',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attendant',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
